#!/bin/bash

#ln -sf  "$OPENSHIFT_HOMEDIR/python/virtenv/lib/python2.7/site-packages/Django-1.6.5-py2.7.egg/django/contrib/admin/static" "$OPENSHIFT_REPO_DIR"mysy/static/

#python "$OPENSHIFT_REPO_DIR"mysy/manage.py collectstatic --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py syncdb --noinput'"
python $OPENSHIFT_REPO_DIR/mysy/manage.py syncdb --noinput

#echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py collectstatic --noinput'"
#python $OPENSHIFT_REPO_DIR/mysy/manage.py collectstatic --noinput
